"""added join table so that projects have many-to-many relationship with skills table

Revision ID: 4a5da6c2cbf4
Revises: 8a92a9e0e68a
Create Date: 2023-10-20 14:17:27.702197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5da6c2cbf4'
down_revision = '8a92a9e0e68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects_skills',
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_projects_skills_project_id_projects')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_projects_skills_skill_id_skills'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('blog', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('about', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about')
        batch_op.drop_column('blog')
        batch_op.drop_column('github')

    op.drop_table('projects_skills')
    # ### end Alembic commands ###
